name: Data Autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * TUE'

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2
    - uses: Andrew-Chen-Wang/district-autoupdate@v1.0.1
      with:
        districts-repo: 'Andrew-Chen-Wang/districts'
        tag-branch: 'non-voting-geojson-update'
        path: ${{ github.workspace }}/districts.geojson
    
    - name: Checkout unitedstates/images
      uses: actions/checkout@v2
      with:
        repository: unitedstates/images
        path: './temp-actions-unitedstates-images'
    - name: Add Congress 450x550 images to repo
      run: |
        rsync -avu --delete ./temp-actions-unitedstates-images/congress/450x550 ./rep-images
        rm -rf ./temp-actions-unitedstates-images

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Autoupdate data
        commit_author: GitHub Actions <actions@github.com>
